### ISSUE TITLE
error if topic title is very short 

### ISSUE THREAD

**Issue by exomarty** [pichalite/nodebb-plugin-topic-tags#1]
tried to set a topic title "ok ok" and getting this error

![captura de pantalla 2016-04-22 a las 1 56 31](https://cloud.githubusercontent.com/assets/10746278/14727659/7afe558c-082d-11e6-95bc-d0ddb9288965.png)

**Comment by pichalite** [comment]
I think the issue is with the length of the tag. added checks for tag length based on ACP setting. try the new version.

**Comment by pichalite** [comment]
fixed here https://github.com/pichalite/nodebb-plugin-topic-tags/commit/de674b39c4a66539e03695b8c9200d0e6dd6eead
