### ISSUE TITLE
Ignored words does not seem to be working

### ISSUE THREAD

**Issue by GitPuffy** [pichalite/nodebb-plugin-topic-tags#2]
I have added two words to the ignored section of the plugin ACP.  They are `screenshot, shot`. 

When I create a new topic post with the word `shot` in the title a tag for shot still gets created.

**Comment by pichalite** [comment]
plugin was not expecting spaces in words. changed logic to trim spaces.

fixed in https://github.com/pichalite/nodebb-plugin-topic-tags/commit/6c8fcc27f6e4b5efecc71e880c7dacacbfd21897
